### ISSUE TITLE
membuat slide untuk poster iklan.

### ISSUE THREAD

**Issue by nardiyansah** [nardiyansah/Minimart#2]
Gimana caranya membuat slide untuk poster iklan, sebelumnya dah nyoba make kode carousel tapi gak jalan. cuman main asal copy paste aja sih.. kayaknya ada kode yang kurang.

**Comment by Revtm** [comment]
apakah issue ini masih dibuka?
saya sudah melakukan percobaan carouselnya di:
https://github.com/nardiyansah/Minimart/tree/master/workshop/labpercobaan

sepertinya berhasil, bisa otomatis sliding dan ada tombol next dan previous slide

**Comment by Revtm** [comment]
jika ingin dicoba, bisa difetch lalu dipull atau langsung pull perubahan project yang terbaru~

**Comment by nardiyansah** [comment]
sudah berhasil gan, arigatou
