### ISSUE TITLE
bagaimana membuat nama karyawan ada di pojok ?

### ISSUE THREAD

**Issue by nardiyansah** [nardiyansah/Minimart#3]

**Comment by Revtm** [comment]
saya sudah coba gan, hasilnya ada di file index.php pada folder menuadmin

(https://github.com/nardiyansah/Minimart/blob/master/workshop/MenuAdmin/index.php)

**Comment by Revtm** [comment]
penggunaan **style= "margin-left:auto;"** ini membuat class atau id nya bisa auto rata kanan mengikuti lebar layar

> 
          <div class="nav-item dropdown" style= "margin-left:auto;" >
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style= "margin-left:auto;">
                @akun_admin
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Profil</a>
                <a class="dropdown-item" href="#">Pengaturan</a>
                <a class="dropdown-item" href="#" style="color:red">Logout</a>
              </div>
          </div>

**Comment by nardiyansah** [comment]
it's work !! thank you gan..
